name: Deploy

on:
  push:
    branches:
      - develop
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt

    - name: Copy code to DigitalOcean
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        source: "."
        target: "/app"
        debug: true

    - name: SSH into DigitalOcean and run application
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DROPLET_IP }}
        username: ${{ secrets.DROPLET_USER }}
        key: ${{ secrets.DROPLET_SSH_KEY }}
        script: |
          cd /app
          sudo apt-get update
          sudo apt-get install -y python3.9 python3-pip python3.9-venv
          python3 -m venv myenv
          source myenv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          # Running the Flask application
          nohup flask run --host=0.0.0.0 &